sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
- "10.9"

cache:
  directories:
  - /home/travis/.cache/Cypress

branches:
  except:
  - master

install:
- yarn install

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- yarn global add codecov

script:
- ng lint
- yarn test:ci
- yarn build:prod

after_success:
- codecov

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  target_branch: master
  on:
    branch: develop