sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
- "10.9"

branches:
  except:
  - master

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm ci
- yarn global add codecov

cache:
  yarn: true

script:
- ng lint
- yarn test:ci
- yarn build:prod

after_success:
- codecov

deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  target_branch: master
  on:
    branch: develop