dist: trusty
addons:
  chrome: stable
os: "linux"

language: node_js
node_js:
- "10.9"

branches:
  except:
  - master

install:
- yarn install

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- yarn global add codecov

script:
- ng lint
- yarn test:ci
- yarn test:ci:e2e
- yarn build:prod

after_success:
- codecov

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./dist/
  target_branch: master
  on:
    branch: pre-deploy