name: "Push Coverage Badge"
description: "Commits and pushes a coverage badge to coverage-badges branch"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Copy badge
      shell: bash
      run: |
        mkdir -p badges
        cp "${{ inputs.badge_path }}" badges/coverage.svg

    - name: Commit and push badge
      shell: bash
      run: |
        git fetch origin

        if git rev-parse --verify origin/coverage-badges >/dev/null 2>&1; then
          git checkout -B coverage-badges origin/coverage-badges
        else
          git checkout --orphan coverage-badges
          git rm -rf . >/dev/null 2>&1 || true
        fi

        mkdir -p badges
        cp "${{ inputs.badge_path }}" badges/coverage.svg

        git add badges/coverage.svg
        git commit -m "chore: update coverage badge [skip ci]" || echo "No changes to commit"
        git push origin HEAD:coverage-badges --force

inputs:
  badge_path:
    description: "Path to the coverage badge to push"
    required: true
