name: Generate Coverage Badge

on:
  workflow_call:
    inputs:
      lcov-path:
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      badge-path: ${{ steps.set-output.outputs.badge-path }}
    steps:
      - uses: actions/checkout@v3

      # Optional: Node.js setup if needed
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Get coverage percentage
        id: coverage
        run: |
          LCOV="${{ inputs.lcov-path }}"
          if [ -z "$LCOV" ]; then
            LCOV=$(find coverage -type f -name lcov.info | head -n1)
          fi

          if [ -z "$LCOV" ] || [ ! -f "$LCOV" ]; then
            echo "coverage=0" >> $GITHUB_OUTPUT
          else
            COVERAGE=$(grep -A 1 TOTAL "$LCOV" | grep -oP '(?<=\s)\d+(?=\.\d+%)' | tail -1)
            echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          fi

      - name: Generate badge
        id: set-output
        run: |
          mkdir -p badges
          COVERAGE=${{ steps.coverage.outputs.coverage }}
          if [ -z "$COVERAGE" ]; then COVERAGE=0; fi

          COLOR=red
          if [ "$COVERAGE" -ge 90 ]; then COLOR=brightgreen
          elif [ "$COVERAGE" -ge 85 ]; then COLOR=green
          elif [ "$COVERAGE" -ge 80 ]; then COLOR=yellow
          fi

          echo "Generating badge for coverage ${COVERAGE}% ($COLOR)"
          curl -s -o badges/coverage.svg "https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}"
          echo "badge-path=badges/coverage.svg" >> $GITHUB_OUTPUT

      - name: Upload badge artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: badges/coverage.svg
