name: "Generate Coverage Badge"
description: "Installs dependencies, runs tests with coverage, and generates a coverage badge"
runs:
  using: "composite"
  steps:
    # -------------------------------
    # Checkout repo
    # -------------------------------
    - name: Checkout repository
      uses: actions/checkout@v3
      shell: bash

    # -------------------------------
    # Setup Node.js
    # -------------------------------
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
      shell: bash

    # -------------------------------
    # Install dependencies
    # -------------------------------
    - name: Install dependencies
      run: yarn install
      shell: bash

    # -------------------------------
    # Run tests with coverage
    # -------------------------------
    - name: Run tests with coverage
      run: yarn test:ci
      shell: bash

    # -------------------------------
    # Get coverage percentage
    # -------------------------------
    - name: Get coverage percentage
      id: coverage
      run: |
        LCOV="${{ inputs.lcov_path }}"
        if [ -z "$LCOV" ]; then
          LCOV=$(find coverage -type f -name lcov.info | head -n1)
        fi

        if [ -z "$LCOV" ] || [ ! -f "$LCOV" ]; then
          echo "coverage=0" >> $GITHUB_OUTPUT
        else
          # Calculate overall line coverage from LH/LF in the LCOV
          COVERAGE=$(awk '
            /^LF:/ { total_lines += $2 }
            /^LH:/ { covered_lines += $2 }
            END {
              if (total_lines > 0) {
                printf("%d", covered_lines / total_lines * 100)
              } else {
                print 0
              }
            }
          ' "$LCOV")

          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
        fi
      shell: bash

    # -------------------------------
    # Generate badge
    # -------------------------------
    - name: Generate badge
      id: set-badge
      run: |
        mkdir -p badges
        COVERAGE=${{ steps.coverage.outputs.coverage }}
        [ -z "$COVERAGE" ] && COVERAGE=0

        COLOR=red
        if [ "$COVERAGE" -ge 90 ]; then COLOR=brightgreen
        elif [ "$COVERAGE" -ge 85 ]; then COLOR=green
        elif [ "$COVERAGE" -ge 80 ]; then COLOR=yellow
        fi

        echo "Generating badge for coverage ${COVERAGE}% ($COLOR)"
        curl -s -o badges/coverage.svg "https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}"

        echo "badge-path=badges/coverage.svg" >> $GITHUB_OUTPUT
      shell: bash

inputs:
  lcov_path:
    description: "Optional path
