name: Deploy to LIVE
on:
  push:
    branches: [pre-deploy]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # install ubuntu deps

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      # install deps
      - run: yarn install

      # build
      - run: yarn build:prod --output-path deploy

      # push to master
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: master # The branch the action should deploy to.
          folder: deploy # The folder the action should deploy.
