name: Deploy to LIVE
on:
  push:
    branches: [pre-deploy]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # install ubuntu deps

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      # build
      - run: yarn build:prod

      # run code coverage
      - uses: EndBug/add-and-commit@v7
        with:
          add: "dist"
          author_name: "cd"
          branch: master

      # run code coverage
      - uses: codecov/codecov-action@v2
